### ISSUE TITLE
Should redirect to home when trying to access restricted page and not logged in

### ISSUE THREAD

**Issue by km333** [claustres/quasar-feathers-tutorial#11] opened 2018-04-14 07:45 UTC
eg.
I am not logged in and navigate to
http://localhost:8080/#/chat

I get a semi-rendered page and left there.
(Can even enter messages which also get silently rejected on back-end)

Backend throws error as it should
info: error: messages - Method: find: No auth token
error:  NotAuthenticated: No auth token
    at new NotAuthenticated (/home/mike/dev/quasar/quasar-feathers-tutorial/quasar-feathers/api/node_modules/@feathersjs/errors/lib/index.js:93:17)

Better to check auth when URL first attempted and redirect to home/signin etc.

**Comment by leob** [comment] 2018-04-14 08:01
Wow, you're right ... my initial test showed that it worked, but when I test again I get the phenomenon that you describe. Probably something with the configuration of Vue/Quasar router ... I'll have a look.

**Comment by km333** [comment] 2018-04-14 08:53
Yeah I believe there's a few ways to do this.
Simplest (I guess without vuex) is using meta in routes.js eg. meta: { requiresAuth: true } },
plus a Router.beforeEach((to, from, next) => {..  in router/index.js
and I think it needs a plugin to expose the api auth call.
There's a helpful quasar issue here I found ( I think):
https://github.com/quasarframework/quasar/issues/1737
and Vue docs for navigation guards:
https://router.vuejs.org/en/advanced/navigation-guards.html

**Comment by claustres** [comment] 2018-04-14 11:43
We have a more complete example in our app template as a source of inspiration: https://github.com/kalisio/kApp/blob/master/src/components/Index.vue#L56 & https://github.com/kalisio/kCore/blob/master/src/client/mixins/mixin.authentication.js.

**Comment by leob** [comment] 2018-04-14 11:57
Well, you are right, there are many ways to fix this.

A simple "quick and dirty" fix is to change the router mode from 'hash' to 'history' (which is actually the default for apps generated by Quasar CLI). Problem solved (but see remarks below).

Note: for more complex apps, "history mode" requires a catch-all route on the backend (as per https://router.vuejs.org/en/essentials/history-mode.html), but for our simple demo app it will actually work without (I've checked this).

Now I said "quick and dirty", because when I then look at my Chrome JS console I stil see the Feathers client throwing an unhandled exception:

```
Uncaught (in promise) NotAuthenticated {type: "FeathersError", name: "NotAuthenticated", message: "No auth token", code: 401, className: "not-authenticated", …}
```
So I'll admit that this is a fairly ugly workaround - the Feathers client throws an unhandled error and then the routing system (if you set it to 'history') then refuses the page change (well that's what I make of it). I believe I also saw a "page flicker" but couldn't make out what that was.

So a better way would indeed be to use Vue router guards, to completely prevent the page/route transition. It would look something like this:

```
router.beforeEach((to, from, next) => {

  if (to.meta.requiresAuth) {

    if (auth.authenticated()) {
      next()
    } else {
      next(false)
    }
  } else {
    next()
  }
})
```

To make this work I need to be able to check (in a lightweight way) if there is an authenticated user. As far as I could see there is no built-in method in the Feathers authentication client to check this, but this is easy to create.

So what I did is I introduced an "auth" module, which would be a simple wrapper around the Feathers API, and which would keep track internally of whether or not there is an authenticated user (this is the module's "authenticated()" method).

If you do it this way then you prevent the Feathers error from being thrown - a slightly more complex but much nicer solution.

I've almost finished this (copy/pasted it from one of my other apps), so I'll commit it. We then need to change the README app a bit however.

**Comment by leob** [comment] 2018-04-14 12:02
@claustres Thanks, doing it with a Vue plugin seems an elegant solution, I've heard about Vue plugins but wasn't familiar enough with them to make it an obvious solution for me. Would this also be a case where Vuex would make sense (in a more complex app where you want to use Vuex anyway) ?

Let me just check in my solution with the 'auth' module (almost finished it anyway), in a next iteration we might refactor that to a plugin.

**Comment by leob** [comment] 2018-04-14 14:03
Checked in my fix with vue-router guards and a new 'auth' module, what remains is to update the text of the tutorial.

**Comment by leob** [comment] 2018-04-14 15:28
Updated the README too, closing this issue now.

**Closed as completed by leob** 2018-04-14 15:28 UTC

**Comment by km333** [comment] 2018-04-15 01:40
Hi @leob thanks for fixing this so quickly
I do have a small problem still though.
If I login then either
- navigate to chat via icon/menu then click refresh in browser (seems like a reasonable use case)
- navigate to http://localhost:8080/chat in browser directly
Then because this.user gets cleared authenticated() fails
I'm not sure what best way around this is.
I thought maybe try at least to authenticate from jwt  in  authenticated () after initial this.user check.
ie. something like

(auth.js)
  authenticated () {
    // session already authenticated no need to go to server
    if ( this.user != null ) return true
    // Check if there is already a session running
    auth.authenticate()
    return this.user != null
  },

Just an idea interested to hear your thoughts

**Comment by leob** [comment] 2018-04-15 03:49
Not really sure what exactly the problem is ...

If you click 'refresh' in the browser then it executes the "mounted" lifecycle method in default.vue, and the default behavior then is to check for an authentication session and redirect back to the home page - if you're logged in then you stay logged in. Seems to me a reasonable behavior for a non-standard action (normally you'd go to the chat page by clicking on a link, not by typing a URL in the browser.

I've checked your suggestion, but it didn't make a difference.

What does help is reverting back to router mode 'hash' instead of 'history'. It's just not working as expected with 'history' mode, with 'hash' it works but the URLs look a bit more ugly.

I could commit this as a quick fix, I'll leave this issue open just in case someone comes up with a better idea.

**Comment by leob** [comment] 2018-04-15 14:44
Okay, I've committed that change - changed router mode from 'history' to 'hash' ... this fully fixes the problem (some unhandled exceptions that I saw previously in the JS console are also gone). Question remains how to get 'history' mode working properly, I'll leave that as a task for whoever is interested.
